### PR TITLE
Add yaml for Kube Deployment

### PR DESCRIPTION
**Pull request by ajbozarth**
Part of https://github.ibm.com/CODAIT/Usability-Enhancement/issues/2

### CODE REVIEW

**Comment by djalova** [comment]
We need to add instruction for kube to the README

**Comment by ajbozarth** [comment]
As mentioned in the linked parent issue, I'll be adding that with my README updates in a followup PR

**Comment by djalova** [comment]
LGTM

**Comment by ajbozarth** [comment]
tested locally

**Pull request merged**
